### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by HalyangDream** [dqh147258/SafeLiveData#1]
实际上调用 observerforever的方法还是会内存泄漏的吧

**Comment by dqh147258** [comment]
确实如此,如果需要实现observerForever的引用自动解除需要使用弱引用并完全重新实现LiveData,这不是装饰器能做到的.
不过我觉得并无必要这样做,毕竟LiveData主要使用的都是observer,而observerForever并不常用,也没必要,毕竟它方法名带了forever就应该知道需要手动移除.
